import { useState } from "react";
import { Award, RefreshCw, BarChart3, ShieldCheck, Share2, Check, FileDown } from "lucide-react";
import { UserProfile } from "../types";
import RadarChart from "./RadarChart";
import { jsPDF } from "jspdf";

const cleanForPdf = (text: string): string => {
  if (!text) return "";
  let result = text
    .replace(/ə/g, "e")
    .replace(/Ə/g, "E")
    .replace(/ı/g, "i")
    .replace(/İ/g, "I")
    .replace(/ş/g, "s")
    .replace(/Ş/g, "S")
    .replace(/ç/g, "c")
    .replace(/Ç/g, "C")
    .replace(/ö/g, "o")
    .replace(/Ö/g, "O")
    .replace(/ğ/g, "g")
    .replace(/Ğ/g, "G")
    .replace(/ü/g, "u")
    .replace(/Ü/g, "U");

  // Filter out any character not in standard printable ASCII range (which includes modern standard emojis and other complex fonts)
  result = result.replace(/[^\x20-\x7E]/g, "");
  return result.trim();
};

interface IdentityResultCardProps {
  profile: UserProfile;
  onReset: () => void;
}

export default function IdentityResultCard({ profile, onReset }: IdentityResultCardProps) {
  const [copied, setCopied] = useState(false);
  const dna = profile.dnaProfile;
  if (!dna) return null;

  const getTraits = () => {
    const bioLower = (profile.customBio || "").toLowerCase();
    const isAzOrTr = /oynamisam|saat|yaxsidir|suretli|reaksiya|gucludur|biler|hassas|oyun|hedshot/i.test(bioLower);

    const traits: string[] = [];
    if (isAzOrTr) {
      if (dna.metrics.strategy > 72) {
        traits.push("Güclü taktiki qərar qəbul etmə qabiliyyəti");
      } else if (dna.metrics.strategy < 45) {
        traits.push("Anlıq ssenari dəyişikliklərinə cəld uyğunlaşma hızı");
      } else {
        traits.push("Rasional mövqe təhlili və xəritə oxuma qabiliyyəti");
      }

      if (dna.metrics.teamwork > 65) {
        traits.push("Stabil komanda əməkdaşlığı və sığorta dəstəyi");
      } else if (dna.metrics.teamwork < 45) {
        traits.push("Yüksək fərdi duel və cinah təzyiqi idarəsi");
      } else {
        traits.push("Dinamik komanda tərkibi doldurma ritmi");
      }

      if (dna.metrics.aggression > 70) {
        traits.push("Yüksək templi döyüş atışması və hərəkət sürəti");
      } else if (dna.metrics.aggression < 45) {
        traits.push("Soyuqqanlı və ehtiyatlı atış mövqeləndirilməsi");
      } else {
        traits.push("Çoxşaxəli oyun janrlarında asanlıqla adaptasiya");
      }
    } else {
      if (dna.metrics.strategy > 72) {
        traits.push("Strong tactical decision making");
      } else if (dna.metrics.strategy < 45) {
        traits.push("Instant active situational response control");
      } else {
        traits.push("Rational spatial analysis and situational positioning");
      }

      if (dna.metrics.teamwork > 65) {
        traits.push("Consistent team contribution");
      } else if (dna.metrics.teamwork < 45) {
        traits.push("Self-sufficient duel dynamics & flank control");
      } else {
        traits.push("Dynamic filling of tactical squad roles");
      }

      if (dna.metrics.aggression > 70) {
        traits.push("High-paced engagement & relentless entry driving");
      } else if (dna.metrics.aggression < 45) {
        traits.push("Patient defensive setups & meticulous zone holds");
      } else {
        traits.push("Adaptable across multiple game genres");
      }
    }
    return traits;
  };

  const handleShare = async () => {
    const traits = getTraits();
    const bioLower = (profile.customBio || "").toLowerCase();
    const isAzOrTr = /oynamisam|saat|yaxsidir|suretli|reaksiya|gucludur|biler|hassas|oyun|hedshot/i.test(bioLower);

    const titleStr = isAzOrTr ? "🧬 MƏNİM OYUNÇU DNT PROFİLİM" : "🧬 MY GAMING DNA PROFILE";
    const metricsStr = isAzOrTr ? "Oyun Tərzi Göstəriciləri" : "Playstyle Metrics";
    const aggressionLabel = isAzOrTr ? "Aqressivlik" : "Aggression";
    const strategyLabel = isAzOrTr ? "Taktika / Strategiya" : "Strategy";
    const teamworkLabel = isAzOrTr ? "Komanda Oyunu" : "Teamwork";
    const badgesLabel = isAzOrTr ? "DNT Nişanları" : "Badges";
    const traitsLabel = isAzOrTr ? "Əsas Özəlliklər" : "Top Traits";
    const generatedByText = isAzOrTr ? "GameDNA tərəfindən yaradılmışdır" : "Generated by GameDNA";
    const discoverText = isAzOrTr ? "Öz oyunçu kimliyinizi kəşf edin." : "Discover your gaming identity.";

    const formattedBadges = dna.badges.map(b => b.startsWith("#") ? b : `#${b}`);

    const shareText = `${titleStr}

${dna.personalityName}

Competitive Tier: ${dna.competitiveTier}

${metricsStr}
• ${aggressionLabel}: ${dna.metrics.aggression}%
• ${strategyLabel}: ${dna.metrics.strategy}%
• ${teamworkLabel}: ${dna.metrics.teamwork}%

${badgesLabel}
${formattedBadges.join("\n")}

${traitsLabel}
• ${traits[0]}
• ${traits[1]}
• ${traits[2]}

${generatedByText}
${discoverText}`;

    try {
      if (navigator.clipboard && navigator.clipboard.writeText) {
        await navigator.clipboard.writeText(shareText);
      } else {
        const textarea = document.createElement("textarea");
        textarea.value = shareText;
        textarea.style.position = "fixed";
        textarea.style.opacity = "0";
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand("copy");
        document.body.removeChild(textarea);
      }
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.warn("Clipboard access failed:", err);
    }
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4" // 210 x 297 mm
    });

    const traits = getTraits();
    const bioLower = (profile.customBio || "").toLowerCase();
    const isAzOrTr = /oynamisam|saat|yaxsidir|suretli|reaksiya|gucludur|biler|hassas|oyun|hedshot/i.test(bioLower);

    // 1. Sleek Cyberpunk Dark Slate Background
    doc.setFillColor(10, 11, 16); // Deep charcoal black
    doc.rect(0, 0, 210, 297, "F");

    // Decorative cyber grid lines / border frames
    doc.setDrawColor(34, 211, 238); // Cyan-400
    doc.setLineWidth(0.8);
    doc.rect(10, 10, 190, 277, "S");
    
    doc.setDrawColor(168, 85, 247); // Purple-500
    doc.setLineWidth(0.3);
    doc.rect(12, 12, 186, 273, "S");

    // Decorative cyberpunk corner notches
    doc.setFillColor(34, 211, 238);
    doc.rect(8, 8, 8, 4, "F");
    doc.rect(8, 8, 4, 8, "F");
    doc.rect(194, 8, 8, 4, "F");
    doc.rect(198, 8, 4, 8, "F");
    doc.rect(8, 285, 8, 4, "F");
    doc.rect(8, 281, 4, 8, "F");
    doc.rect(194, 285, 8, 4, "F");
    doc.rect(198, 281, 4, 8, "F");

    // 2. Header text - GAMING DNT PROFILE
    doc.setTextColor(34, 211, 238); // Cyan
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(cleanForPdf(isAzOrTr ? "OYUNCU QUANTUM DNT ANALIZI // AKTIV SKELETON VERIFIED" : "GAMING NEUROMORPHIC DETECTOR // QUANTUM SEQUENCE ACTIVE"), 20, 25);

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(26);
    doc.text(cleanForPdf(isAzOrTr ? "OYUNCU DNT PROFILI" : "GAMING DNA PROFILE"), 20, 38);

    // Divider
    doc.setFillColor(255, 255, 255, 0.1);
    doc.rect(20, 44, 170, 0.5, "F");

    // 3. User Codename details
    doc.setTextColor(148, 163, 184); // Slate
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.text(cleanForPdf(isAzOrTr ? "ISTIFADECI ADI:" : "SUBJECT CODENAME:"), 20, 54);
    
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text(cleanForPdf(profile.username.toUpperCase()), 20, 62);

    doc.setTextColor(34, 211, 238);
    doc.setFontSize(11);
    const reliabilityLabel = isAzOrTr ? `DEQIKLIK NISBETI: ${dna.analysisReliability}%` : `SEQUENCE STATUS: VERIFIED // RELIABILITY: ${dna.analysisReliability}% ACCURACY`;
    doc.text(cleanForPdf(reliabilityLabel), 20, 69);

    // 4. Central Large Archetype Banner Box
    doc.setFillColor(15, 23, 42); // Navy slate background
    doc.rect(20, 77, 170, 28, "F");
    doc.setDrawColor(168, 85, 247); // Purple
    doc.setLineWidth(0.5);
    doc.rect(20, 77, 170, 28, "S");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.text(cleanForPdf(dna.personalityName), 25, 88);

    doc.setTextColor(168, 85, 247); // Purple
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    const ratingLabel = isAzOrTr ? `REQABETLI SEVIYYE: ${dna.competitiveTier}` : `COMPETITIVE RATING: ${dna.competitiveTier}`;
    doc.text(cleanForPdf(ratingLabel), 25, 96);

    // 5. Playstyle metrics details (Aggression, Strategy, Teamwork)
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(cleanForPdf(isAzOrTr ? "OYUN TERZI GOSTERICILERI" : "PLAYSTYLE METRICS"), 20, 120);

    // Aggression bar
    doc.setTextColor(244, 63, 94); // Rose
    doc.setFontSize(11);
    const aggrText = isAzOrTr ? `Aqressivlik: ${dna.metrics.aggression}%` : `Aggression: ${dna.metrics.aggression}%`;
    doc.text(cleanForPdf(aggrText), 20, 130);
    doc.setFillColor(30, 41, 59); // Track
    doc.rect(20, 133, 170, 4, "F");
    doc.setFillColor(244, 63, 94); // Bar fill
    doc.rect(20, 133, 1.7 * dna.metrics.aggression, 4, "F");

    // Strategy bar
    doc.setTextColor(34, 211, 238); // Cyan
    doc.setFontSize(11);
    const stratText = isAzOrTr ? `Strategiya: ${dna.metrics.strategy}%` : `Strategy: ${dna.metrics.strategy}%`;
    doc.text(cleanForPdf(stratText), 20, 145);
    doc.setFillColor(30, 41, 59); // Track
    doc.rect(20, 148, 170, 4, "F");
    doc.setFillColor(34, 211, 238); // Bar fill
    doc.rect(20, 148, 1.7 * dna.metrics.strategy, 4, "F");

    // Teamwork bar
    doc.setTextColor(168, 85, 247); // Purple
    doc.setFontSize(11);
    const teamText = isAzOrTr ? `Komanda Oyunu: ${dna.metrics.teamwork}%` : `Teamwork: ${dna.metrics.teamwork}%`;
    doc.text(cleanForPdf(teamText), 20, 160);
    doc.setFillColor(30, 41, 59); // Track
    doc.rect(20, 163, 170, 4, "F");
    doc.setFillColor(168, 85, 247); // Bar fill
    doc.rect(20, 163, 1.7 * dna.metrics.teamwork, 4, "F");

    // 6. Badges block
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(cleanForPdf(isAzOrTr ? "AKTIV TRAIT NISANLARI" : "ACTIVE TRAIT SIGNATURE BADGES"), 20, 182);

    let badgeY = 192;
    dna.badges.forEach((badge) => {
      doc.setFillColor(30, 41, 59, 0.4);
      doc.rect(20, badgeY - 5, 170, 8, "F");
      
      doc.setTextColor(34, 211, 238);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      const formattedBadge = badge.startsWith("#") ? badge : `#${badge}`;
      doc.text(cleanForPdf(formattedBadge), 25, badgeY);
      badgeY += 10;
    });

    // 7. Top Traits
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(cleanForPdf(isAzOrTr ? "ESAS OZELLIKLER" : "TOP DIAGNOSTIC TRAITS"), 20, badgeY + 5);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(226, 232, 240); // Slate-200

    let traitY = badgeY + 15;
    traits.forEach((trait) => {
      doc.text(`- ${cleanForPdf(trait)}`, 20, traitY);
      traitY += 8;
    });

    // 8. Footer credits
    doc.setFillColor(255, 255, 255, 0.05);
    doc.rect(20, 260, 170, 0.5, "F");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184); // Slate-400
    doc.text(cleanForPdf(isAzOrTr ? "GameDNA Kvant Diaqnostika Sistemi terefinden hazirlanmisdir" : "Generated by GameDNA Quantum Diagnostic Engine"), 20, 268);
    doc.text(cleanForPdf(isAzOrTr ? "Oz oyuncu kimliyinizi tehlukesiz sekilde kesf edin. Skan bitti." : "Discover your gaming identity securely. Scan complete."), 20, 273);

    // Save PDF file
    doc.save(`${cleanForPdf(profile.username)}_GameDNA_Profile.pdf`);
  };

  return (
    <div id="results-master-card" className="grid gap-6 lg:grid-cols-12 items-stretch">
      
      {/* 1. Main Highlights Box (Left panel: 8 cols) */}
      <div className="lg:col-span-8 glass-effect rounded-3xl p-6 md:p-8 relative overflow-hidden flex flex-col justify-between shadow-2xl">
        
        {/* Glow vector spot */}
        <div className="pointer-events-none absolute right-0 top-0 h-48 w-48 rounded-full bg-cyan-500/10 blur-[80px]" />
        
        <div id="result-badge-row" className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-6">
          <div className="flex items-center gap-2.5">
            <span className="rounded-full bg-cyan-500/10 border border-cyan-500/30 px-3 py-1 text-[9px] text-cyan-400 font-mono tracking-widest uppercase font-bold">
              PROFILE ANALYZED // ACTIVE HABITS
            </span>
            <span className="text-[10px] text-slate-500 font-mono font-bold uppercase tracking-wider hidden xs:inline">
              SEQUENCE_ID: #{profile.id.replace("u_", "").toUpperCase()}
            </span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleShare}
              id="share-profile-btn-badge"
              className="flex items-center justify-center gap-1.5 rounded-full bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-400 hover:text-cyan-300 border border-cyan-500/30 px-3.5 py-1 text-[10px] font-mono tracking-wider uppercase font-bold transition cursor-pointer select-none"
            >
              {copied ? (
                <>
                  <Check className="h-3 w-3 text-emerald-400" />
                  <span>COPIED!</span>
                </>
              ) : (
                <>
                  <Share2 className="h-3 w-3 animate-pulse" />
                  <span>SHARE DNA Profile</span>
                </>
              )}
            </button>

            <button
              onClick={handleDownloadPDF}
              id="download-pdf-btn-badge"
              className="flex items-center justify-center gap-1.5 rounded-full bg-purple-500/10 hover:bg-purple-500/20 text-purple-400 hover:text-purple-300 border border-purple-500/30 px-3.5 py-1 text-[10px] font-mono tracking-wider uppercase font-bold transition cursor-pointer select-none"
            >
              <FileDown className="h-3.5 w-3.5" />
              <span>DOWNLOAD PDF</span>
            </button>
          </div>
        </div>

        {/* Balanced Grid for Profile Details & D3 Radar Chart */}
        <div id="highlights-interactive-grid" className="grid gap-6 md:grid-cols-12 items-center mb-8">
          
          {/* Left: User Identity avatar & description */}
          <div id="identity-header-grid" className="md:col-span-7 flex flex-col md:flex-row items-center gap-6">
            
            {/* Avatar cylinder with cyan rings */}
            <div className="relative shrink-0 select-none mx-auto md:mx-0">
              <div className="absolute inset-0 rounded-full bg-gradient-to-tr from-cyan-400 via-blue-500 to-purple-600 animate-[spin_8s_linear_infinite]" />
              <div className="absolute inset-[3px] rounded-full bg-[#0a0b10]" />
              <img
                referrerPolicy="no-referrer"
                src={profile.avatarUrl}
                alt={profile.username}
                className="relative z-10 rounded-full h-24 w-24 object-cover border border-white/5"
              />
            </div>

            <div className="flex-1 text-center md:text-left">
              <span className="text-[10px] text-slate-400 uppercase tracking-widest font-mono font-bold">YOUR COMPILER GENOTYPE</span>
              <h1 className="font-sans text-2xl md:text-3xl font-black text-white uppercase tracking-tight mt-1.5 leading-none">
                {dna.personalityName}
              </h1>
              <p className="text-xs text-slate-350 mt-4 leading-relaxed uppercase font-semibold tracking-wider">
                {dna.description}
              </p>
            </div>

          </div>

          {/* Right: D3 Radar Chart */}
          <div id="radar-chart-panel" className="md:col-span-5 flex justify-center">
            <RadarChart metrics={dna.metrics} />
          </div>

        </div>

        {/* Badges list row */}
        <div id="dna-badges-list" className="flex flex-wrap gap-2.5 mb-4 border-t border-white/5 pt-6 font-mono font-bold">
          {dna.badges.map((badge, idx) => (
            <span
              key={idx}
              className="rounded-full bg-white/5 border border-white/10 px-3.5 py-1 text-[10px] text-cyan-400 uppercase tracking-wider"
            >
              {badge}
            </span>
          ))}
          <span className="rounded-full bg-purple-500/10 border border-purple-500/20 px-3.5 py-1 text-[10px] text-purple-400 uppercase tracking-wider">
            #{dna.competitiveTier.replace(/\s+/g, "").toUpperCase()}
          </span>
        </div>

      </div>

      {/* 2. Side metrics & triggers (Right panel: 4 cols) */}
      <div className="lg:col-span-4 flex flex-col gap-6 justify-between">
        
        {/* Playstyle Metrics sliders */}
        <div className="glass-effect rounded-3xl p-6 relative flex-1 flex flex-col justify-between shadow-2xl">
          <div>
            <h3 className="font-sans text-[10px] font-bold text-white uppercase tracking-widest mb-6 flex items-center gap-1.5 font-mono">
              <BarChart3 className="h-4 w-4 text-cyan-400 animate-pulse" /> PLAYSTYLE METRICS
            </h3>

            <div id="sliders-bars-container" className="flex flex-col gap-4 font-mono">
              {/* Metric 1 */}
              <div>
                <div className="flex justify-between items-center text-[10px] mb-1.5 font-bold">
                  <span className="text-slate-400 uppercase tracking-wider">AGGRESSION</span>
                  <span className="text-rose-400">{dna.metrics.aggression}%</span>
                </div>
                <div className="h-1.5 w-full bg-[#0a0b10] border border-white/5 rounded-full overflow-hidden">
                  <div
                    style={{ width: `${dna.metrics.aggression}%` }}
                    className="bg-gradient-to-r from-rose-650 to-rose-450 h-full rounded-full shadow-[0_0_8px_#f43f5e]"
                  />
                </div>
              </div>

              {/* Metric 2 */}
              <div>
                <div className="flex justify-between items-center text-[10px] mb-1.5 font-bold">
                  <span className="text-slate-400 uppercase tracking-wider">STRATEGY</span>
                  <span className="text-cyan-400">{dna.metrics.strategy}%</span>
                </div>
                <div className="h-1.5 w-full bg-[#0a0b10] border border-white/5 rounded-full overflow-hidden">
                  <div
                    style={{ width: `${dna.metrics.strategy}%` }}
                    className="bg-gradient-to-r from-cyan-600 to-cyan-450 h-full rounded-full shadow-[0_0_8px_#06b6d4]"
                  />
                </div>
              </div>

              {/* Metric 3 */}
              <div>
                <div className="flex justify-between items-center text-[10px] mb-1.5 font-bold">
                  <span className="text-slate-400 uppercase tracking-wider">TEAMWORK</span>
                  <span className="text-purple-400">{dna.metrics.teamwork}%</span>
                </div>
                <div className="h-1.5 w-full bg-[#0a0b10] border border-white/5 rounded-full overflow-hidden">
                  <div
                    style={{ width: `${dna.metrics.teamwork}%` }}
                    className="bg-gradient-to-r from-purple-650 to-purple-450 h-full rounded-full shadow-[0_0_8px_#a855f7]"
                  />
                </div>
              </div>
            </div>
          </div>

          <div className="mt-6 border-t border-white/5 pt-4 flex items-center justify-between font-mono font-bold">
            <span className="text-[9px] text-slate-500 uppercase tracking-widest">RELIABILITY INDEX</span>
            <span className="text-[10px] text-cyan-400 tracking-wider uppercase">{dna.analysisReliability}% ACCURACY</span>
          </div>

        </div>

        {/* Competitive Toggles box */}
        <div className="glass-effect rounded-3xl p-5 flex items-center gap-4 shadow-xl">
          <div className="h-10 w-10 shrink-0 rounded-xl bg-purple-500/10 border border-purple-500/40 flex items-center justify-center text-purple-400 shadow-[0_0_10px_rgba(168,85,247,0.15)]">
            <ShieldCheck className="h-5 w-5" />
          </div>
          <div className="flex-1 uppercase font-semibold">
            <h4 className="text-[10px] font-bold text-white tracking-widest font-sans">COMPETITIVE SHIELD</h4>
            <p className="text-[9px] text-slate-500 tracking-wider mt-0.5">
              Qualified for {dna.competitiveTier} matching servers.
            </p>
          </div>
          <button
            onClick={onReset}
            className="rounded-lg bg-white/5 hover:bg-white/15 text-slate-400 hover:text-white p-2.5 transition shrink-0 cursor-pointer border border-white/10"
            title="Re-run DNA Sequencing"
          >
            <RefreshCw className="h-3.5 w-3.5" />
          </button>
        </div>

      </div>

    </div>
  );
}
